---
version: '3.8'

services:
  node_exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'

  docker_exporter:
    image: prometheusnet/docker_exporter
    container_name: docker_exporter
    ports:
      - "9417:9417"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    
